import './globals.css'
import '@fontsource/inter'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className="min-h-screen bg-gray-100 dark:bg-slate-900">
        {children}
      </body>
    </html>
  );
}
